config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :students, only: [:create, :index, :show, :new, :edit, :update]
  resources :courses, only: [:create, :index, :show, :new, :edit, :update]
  resources :classrooms, only: [:create, :index, :show, :new]
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  validates :student_id, :course_id, presence: true
  belongs_to :student
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, :description, presence: true
  has_many :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true
  has_many :classrooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:edit, :update, :show]
  before_action :set_collections, only: [:new, :create]

  def index
    @classrooms = Classroom.all
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      redirect_to @classroom
    else
      render :new
    end
  end

  def show
  end

  private

  def set_collections
    @students = Student.all
    @courses = Course.all
  end

  def classroom_params
    params.require(:classroom)
          .permit(:student_id, :course_id)
  end

  def set_classroom
    @classroom = Classroom.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :show]
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  def show
  end

  private

  def course_params
    params.require(:course)
          .permit(:name, :description, :status)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @students = Student.all
    @courses = Course.all
    @classrooms = Classroom.all
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:edit, :update, :show]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to @student
    else
      render :edit
    end
  end

  def show
  end

  private

  def student_params
    params.require(:student)
          .permit(:name, :status)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classrooms/index.html.erb
<div class="page-header">
   <h1>Lista de Classes</h1>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
      <table id="classrooms" class='table table-striped'>
        <thead>
          <tr>
            <th>ID</th>
            <th>Nome do curso</th>
            <th>Nome do estudante</th>
          </tr>
        </thead>
        <tbody>
          <% @classrooms.each do |classroom| %>
          <tr>
            <td><%= link_to classroom.id, classroom %></td>
            <td><%= classroom.course.name %></td>
            <td><%= classroom.student.name %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Nova', new_classroom_path,class: "btn btn-success pull-right" %>
  </div>
</div>

app/views/classrooms/new.html.erb
<h3>Nova Classe</h3>
<%= simple_form_for @classroom do |f| %>
  <%= f.association :course, label: "Curso" %>
  <%= f.association :student, label: "Estudante" %>
  <%= f.button :submit, 'Criar classe', class:"btn btn-primary"  %>
<% end  %>

app/views/classrooms/show.html.erb
<div class="page-header">
  <h1>Classe: <%= @classroom.id %></h1>
</div>

<dl id="classroom-details" class="dl-horizontal">
  <dt>Curso</dt>
  <dd><%= @classroom.course.name %></dd>
  <dt>Estudante</dt>
  <dd><%= @classroom.student.name %></dd>
  <dt>Criado em</dt>
  <dd><%= @classroom.created_at %></dd>
</dl>

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  <%= f.input :name, label: 'Nome' %>
  <%= f.input :description, label: 'Descrição' %>
  <%= f.button :submit, submit_text, class:"btn btn-primary"  %>
<% end  %>

app/views/courses/edit.html.erb
<h3>Atualizar Curso</h3>
<%= render partial: 'form', locals: {submit_text: 'Atualizar curso'} %>

app/views/courses/index.html.erb
<div class="page-header">
   <h1>Lista de Cursos</h1>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
      <table id="courses" class='table table-striped'>
        <thead>
          <tr>
            <th>Nome do curso</th>
            <th>Descrição</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
          <tr>
            <td><%= link_to course.name, course %></td>
            <td><%= course.description %></td>
            <td><%= course.status %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Novo', new_course_path,class: "btn btn-success pull-right" %>
  </div>
</div>

app/views/courses/new.html.erb
<h3>Novo Curso</h3>
<%= render partial: 'form', locals: {submit_text: 'Criar curso'} %>

app/views/courses/show.html.erb
<div class="page-header">
  <h1>Curso: <%= @course.name %></h1>
</div>

<dl id="course-details" class="dl-horizontal">
  <dt>Descrição</dt>
  <dd><%= @course.description %></dd>
  <dt>Status</dt>
  <dd><%= @course.status %></dd>
</dl>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="container">
      <h3>Lista de Cursos</h3>
      <table id="courses" class='table table-striped'>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
          <tr>
            <td class="text-left"><%= course.name %></td>
            <td class="text-left"><%= course.description %></td>
            <td class="text-left"><%= course.status%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <h3>Lista de Estudantes</h3>
      <table id="students" class='table table-striped'>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Número de registro</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
          <tr>
            <td class="text-left"><%= student.name %></td>
            <td class="text-left"><%= student.id %></td>
            <td class="text-left"><%= student.status%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <h3>Lista de Classes</h3>
      <table id="courses" class='table table-striped'>
        <thead>
          <tr>
            <th>ID</th>
            <th>Curso</th>
            <th>Estudante</th>
          </tr>
        </thead>
        <tbody>
          <% @classrooms.each do |classroom| %>
          <tr>
            <td class="text-left"><%= classroom.id %></td>
            <td class="text-left"><%= classroom.course.name %></td>
            <td class="text-left"><%= classroom.student.name%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Enrollment</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <%= link_to "Enrollment", root_path, {class:"navbar-brand"} %>
          </div>
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Novo estudante", new_student_path %>
            </li>
            <li>
              <%= link_to "Novo curso", new_course_path %>
            </li>
            <li>
              <%= link_to "Nova classe", new_classroom_path %>
            </li>
        </div>
      </nav>

      <div class="row">
        <% if flash[:success] %>
        <div class="col-md-12 col-sm-12">
          <div class="alert alert-success alert-dismissible pull-right" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">x</span>
            </button>
            <%= flash[:success] %>
          </div>
        </div>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>
  <%= f.input :name, label: 'Nome' %>
  <%= f.button :submit, submit_text, class:"btn btn-primary"  %>
<% end  %>

app/views/students/edit.html.erb
<h3>Atualizar estudante</h3>
<%= render partial: 'form', locals: {submit_text: 'Atualizar estudante'} %>

app/views/students/index.html.erb
<div class="page-header">
   <h1>Lista de Estudantes</h1>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
      <table id="students" class='table table-striped'>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Número de registro</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
          <tr>
            <td><%= link_to student.name, student %></td>
            <td><%= student.id %></td>
            <td><%= student.status %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Novo', new_student_path,class: "btn btn-success pull-right" %>
  </div>
</div>

app/views/students/new.html.erb
<h3>Novo Estudante</h3>
<%= render partial: 'form', locals: {submit_text: 'Criar estudante'} %>

app/views/students/show.html.erb
<div class="page-header">
  <h1>Estudante: <%= @student.name %></h1>
</div>

<dl id="student-details" class="dl-horizontal">
  <dt>Número de registro</dt>
  <dd><%= @student.id %></dd>
  <dt>Status</dt>
  <dd><%= @student.status %></dd>
</dl>